### PR TITLE
Deprecate settings, introduce loadout stats per class

### PR DESCRIPTION
**Pull request by bhollis**
1. Add a setting for storing stat order/ignored-ness separately per class.
2. Remove, with some prejudice, all the old deprecated settings. They won't even be returned by the API if they're stored.

### CODE REVIEW

**Review by nev-r — APPROVED** [review]
:ok_hand:

**Review by ryan-rushton — APPROVED** [review]
Looks good.

Regarding the armour upgrade stuff, is the plan to keep that in the app? I wonder if it's worth just caching it in local storage?

**Comment by bhollis** [comment]
What armor upgrade stuff?

**Comment by ryan-rushton** [comment]
The upgradeSpendTier and lockEnergy settings. I'm going to rename them now you are deleting them from the API btw.

**Comment by bhollis** [comment]
They moved into `loParameters` a few weeks ago...

**Comment by ryan-rushton** [comment]
Urgh, I totally missed that. Disregard me and my comments

**Pull request merged**
